/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sabab
 */
package all_chat;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class addFriendScreen extends javax.swing.JFrame {

    /**
     * Creates new form addFriendScreen
     */
	private void setIcon() {
		setIconImage(new ImageIcon(getClass().getResource("icon.png")).getImage());
	}
	private String username,password;
    public addFriendScreen(String username,String password) {
    	this.username=username;
    	this.password=password;
        initComponents();
        setIcon();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setMaximumSize(new java.awt.Dimension(643, 60));
        jPanel2.setMinimumSize(new java.awt.Dimension(643, 60));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("_");
        jLabel5.setToolTipText("");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5minimize(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5hoverOnTopLabels(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5exitOnTopLabels(evt);
            }
        });
        jPanel3.add(jLabel5);

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6exit(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6hoverOnTopLabels(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6exitOnTopLabels(evt);
            }
        });
        jPanel3.add(jLabel6);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4goToLink(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4hoverEffectOnLink(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4outEffectOnLink(evt);
            }
        });
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Go Back");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1enterGoBackButton(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1exitGoBackButton(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1GoBackToMainScreen(evt);
            }
        });
        jPanel4.add(jButton1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 362, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red, 2));

        jButton2.setBackground(java.awt.Color.red);
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Friend's Username :");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5minimize(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5minimize
        // TODO add your handling code here:
    	setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel5minimize

    private void jLabel5hoverOnTopLabels(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5hoverOnTopLabels
        // TODO add your handling code here:
    	JLabel temp = (JLabel) evt.getSource();
		temp.setBackground(Color.red);
    }//GEN-LAST:event_jLabel5hoverOnTopLabels

    private void jLabel5exitOnTopLabels(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5exitOnTopLabels
        // TODO add your handling code here:
    	JLabel temp = (JLabel) evt.getSource();
		temp.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jLabel5exitOnTopLabels

    private void jLabel6exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6exit
        // TODO add your handling code here:
    	mainScreen.changeAva();
    	System.exit(0);
    }//GEN-LAST:event_jLabel6exit

    private void jLabel6hoverOnTopLabels(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6hoverOnTopLabels
        // TODO add your handling code here:
    	JLabel temp = (JLabel) evt.getSource();
		temp.setBackground(Color.red);
    }//GEN-LAST:event_jLabel6hoverOnTopLabels

    private void jLabel6exitOnTopLabels(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6exitOnTopLabels
        // TODO add your handling code here:
    	JLabel temp = (JLabel) evt.getSource();
		temp.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jLabel6exitOnTopLabels

    private void jButton1enterGoBackButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1enterGoBackButton
        // TODO add your handling code here:
    	jButton1.setBackground(Color.white);
    	jButton1.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_jButton1enterGoBackButton

    private void jButton1exitGoBackButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1exitGoBackButton
        // TODO add your handling code here:
    	jButton1.setBackground(new Color(102,102,102));
    	jButton1.setForeground(Color.white);
    }//GEN-LAST:event_jButton1exitGoBackButton

    private void jButton1GoBackToMainScreen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1GoBackToMainScreen
        // TODO add your handling code here:
    	dispose();
    	new mainScreen(username,password).setVisible(true);
    }//GEN-LAST:event_jButton1GoBackToMainScreen

    private void jPanel4goToLink(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4goToLink
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4goToLink

    private void jPanel4hoverEffectOnLink(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4hoverEffectOnLink
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4hoverEffectOnLink

    private void jPanel4outEffectOnLink(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4outEffectOnLink
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4outEffectOnLink

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    	String fUsername=jTextField1.getText();
    	if(fUsername.trim().equals("")) {
    		jLabel2.setText("Empty Field.");
    		jLabel2.setForeground(Color.red);
    	}
    	else {
    		if(fUsername.equals(username)) {
    			jLabel2.setText("Invalid username.");
    			jLabel2.setForeground(Color.red);
    		}
    		else {
        		
        		try {
        			Connection conn = DriverManager.getConnection(DBInfo.db, DBInfo.user, DBInfo.pass);
        			Statement stmt = conn.createStatement();
        			String query="SELECT * FROM users WHERE BINARY username='"+fUsername+"'";
        			ResultSet result=stmt.executeQuery(query);
        			if(result.next()) {
        				String query2="SELECT * FROM friends WHERE BINARY user1='"+username+"' AND BINARY user2='"+fUsername+"' OR BINARY user1='"+fUsername+"' AND BINARY user2='"+username+"'";
        				ResultSet result2=stmt.executeQuery(query2);
        				if(result2.next()) {
        					jLabel2.setText("Already a friend.");
        	    			jLabel2.setForeground(Color.red);
        				}
        				else {
        					String query3="INSERT INTO friends VALUES ('"+username+"','"+fUsername+"')";
        					stmt.executeUpdate(query3);
        					String tablename=""+username+""+fUsername;
        					String query4="CREATE TABLE "+tablename+"(fromwho varchar(1000) , message varchar(1000),pos varchar(1000))";
        					stmt.executeUpdate(query4);
        					jLabel2.setText("Successfully Added.");
            				jLabel2.setForeground(Color.green);
            				jTextField1.setText("");
        				}
        			}
        			else {
        				jLabel2.setText("Username is not valid.");
        				jLabel2.setForeground(Color.red);
        			}
        			stmt.close();
        			conn.close();
        		}
        		catch (Exception ex) {
        			JOptionPane.showMessageDialog(null, "" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        		}
    		}
    	}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addFriendScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addFriendScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addFriendScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addFriendScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addFriendScreen(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
