package all_chat;
import java.awt.Color;
import java.awt.Desktop;
import java.net.URI;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

public class createAccountScreen extends javax.swing.JFrame {

    /**
     * Creates new form createAccountScreen
     */
    int tempFocused1 = 1;
    int tempFocused2 = 1;
    int tempFocused3 = 1;
    int tempLastText1 = 1;
    int tempLastText2 = 1;
    int tempLastText3 = 1;

    private void setIcon() {
    	setIconImage(new ImageIcon(getClass().getResource("icon.png")).getImage());
	}
    public createAccountScreen() {
        initComponents();
        setIcon();
        setLocationRelativeTo(null);
        jPasswordField1.setEchoChar('\u0000');
        jPasswordField2.setEchoChar('\u0000');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(664, 638));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setMaximumSize(new java.awt.Dimension(643, 60));
        jPanel2.setMinimumSize(new java.awt.Dimension(643, 60));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("_");
        jLabel5.setToolTipText("");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5minimize(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5hoverOnTopLabels(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5exitOnTopLabels(evt);
            }
        });
        jPanel3.add(jLabel5);

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6exit(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6hoverOnTopLabels(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6exitOnTopLabels(evt);
            }
        });
        jPanel3.add(jLabel6);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4goToLink(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4hoverEffectOnLink(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4outEffectOnLink(evt);
            }
        });
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("All");
        jPanel4.add(jLabel3);

        jLabel1.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Chat");
        jPanel4.add(jLabel1);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Go Back");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enterGoBackButton(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitGoBackButton(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackToLoginScreen(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setForeground(java.awt.Color.blue);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Username");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        jTextField1.setFocusable(false);
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1fieldFocus(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1lostFocusField(evt);
            }
        });
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField1enterField(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1fieldTyped(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPasswordField1.setForeground(java.awt.Color.blue);
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setText("Password");
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        jPasswordField1.setFocusable(false);
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1fieldFocus(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1lostFocusField(evt);
            }
        });
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPasswordField1enterField(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1fieldTyped(evt);
            }
        });

        jPasswordField2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPasswordField2.setForeground(java.awt.Color.blue);
        jPasswordField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField2.setText("Confirm Password");
        jPasswordField2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        jPasswordField2.setFocusable(false);
        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField2fieldFocus(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField2lostFocusField(evt);
            }
        });
        jPasswordField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPasswordField2enterField(evt);
            }
        });
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField2fieldTyped(evt);
            }
        });

        jLabel2.setBackground(java.awt.Color.lightGray);
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("i");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showUsernameReq(evt);
            }
        });

        jLabel4.setBackground(java.awt.Color.lightGray);
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("i");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showPassReq(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sign Up");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusable(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2loginButtonHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2loginButtonOut(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccount(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPasswordField1)
                    .addComponent(jTextField1)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(164, 164, 164))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5minimize(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5minimize
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel5minimize

    private void jLabel5hoverOnTopLabels(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5hoverOnTopLabels
        // TODO add your handling code here:
        JLabel temp = (JLabel) evt.getSource();
        temp.setBackground(Color.red);
    }//GEN-LAST:event_jLabel5hoverOnTopLabels

    private void jLabel5exitOnTopLabels(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5exitOnTopLabels
        // TODO add your handling code here:
        JLabel temp = (JLabel) evt.getSource();
        temp.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jLabel5exitOnTopLabels

    private void jLabel6exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6exit
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6exit

    private void jLabel6hoverOnTopLabels(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6hoverOnTopLabels
        // TODO add your handling code here:
        JLabel temp = (JLabel) evt.getSource();
        temp.setBackground(Color.red);
    }//GEN-LAST:event_jLabel6hoverOnTopLabels

    private void jLabel6exitOnTopLabels(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6exitOnTopLabels
        // TODO add your handling code here:
        JLabel temp = (JLabel) evt.getSource();
        temp.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_jLabel6exitOnTopLabels

    private void jPanel4goToLink(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4goToLink
        try {
            Desktop.getDesktop().browse(new URI("http://allchat.lovestoblog.com/"));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jPanel4goToLink

    private void jPanel4hoverEffectOnLink(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4hoverEffectOnLink
        // TODO add your handling code here:
        jPanel4.setBackground(Color.white);
    }//GEN-LAST:event_jPanel4hoverEffectOnLink

    private void jPanel4outEffectOnLink(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4outEffectOnLink
        // TODO add your handling code here:
        jPanel4.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_jPanel4outEffectOnLink

    private void jTextField1fieldFocus(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1fieldFocus
        // TODO add your handling code here:
        if (evt.getSource() == jTextField1) {
            jTextField1.setBorder(new LineBorder(Color.blue, 5));
            if (jTextField1.getText().trim().equals("") || tempFocused1 == 1 || tempLastText1 == 1) {
                jTextField1.setText("");
                jTextField1.setForeground(Color.black);
            }
        } else if (evt.getSource() == jPasswordField1) {
            jPasswordField1.setBorder(new LineBorder(Color.blue, 5));
            if (jPasswordField1.getText().trim().equals("") || tempFocused2 == 1 || tempLastText2 == 1) {
                jPasswordField1.setText("");
                jPasswordField1.setForeground(Color.black);
                jPasswordField1.setEchoChar('\u2022');
            }
        }
    }//GEN-LAST:event_jTextField1fieldFocus

    private void jTextField1lostFocusField(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1lostFocusField
        // TODO add your handling code here:
        if (evt.getSource() == jTextField1) {
            jTextField1.setBorder(new LineBorder(Color.blue, 2));
            if (jTextField1.getText().trim().equals("")) {
                jTextField1.setText("Username");
                jTextField1.setForeground(Color.BLUE);
                tempLastText1 = 1;
            }
        } else if (evt.getSource() == jPasswordField1) {
            jPasswordField1.setBorder(new LineBorder(Color.blue, 2));
            if (jPasswordField1.getText().trim().equals("")) {
                jPasswordField1.setText("Password");
                jPasswordField1.setForeground(Color.BLUE);
                tempLastText2 = 1;
                jPasswordField1.setEchoChar('\u0000');
            }
        }
    }//GEN-LAST:event_jTextField1lostFocusField

    private void jTextField1enterField(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1enterField
        // TODO add your handling code here:
        if (evt.getSource() == jTextField1) {
            jTextField1.setFocusable(true);

        } else if (evt.getSource() == jPasswordField1) {
            jPasswordField1.setFocusable(true);

        }
    }//GEN-LAST:event_jTextField1enterField

    private void jTextField1fieldTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1fieldTyped
        // TODO add your handling code here:
        if (evt.getSource() == jTextField1) {
            tempFocused1 = 0;
            tempLastText1 = 0;
        } else if (evt.getSource() == jPasswordField1) {
            tempFocused2 = 0;
            tempLastText2 = 0;
        }
    }//GEN-LAST:event_jTextField1fieldTyped

    private void jPasswordField1fieldFocus(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1fieldFocus
        // TODO add your handling code here:
        if (evt.getSource() == jTextField1) {
            jTextField1.setBorder(new LineBorder(Color.blue, 5));
            if (jTextField1.getText().trim().equals("") || tempFocused1 == 1 || tempLastText1 == 1) {
                jTextField1.setText("");
                jTextField1.setForeground(Color.black);
            }
        } else if (evt.getSource() == jPasswordField1) {
            jPasswordField1.setBorder(new LineBorder(Color.blue, 5));
            if (jPasswordField1.getText().trim().equals("") || tempFocused2 == 1 || tempLastText2 == 1) {
                jPasswordField1.setText("");
                jPasswordField1.setForeground(Color.black);
                jPasswordField1.setEchoChar('\u2022');
            }
        }
    }//GEN-LAST:event_jPasswordField1fieldFocus

    private void jPasswordField1lostFocusField(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1lostFocusField
        // TODO add your handling code here:
        if (evt.getSource() == jTextField1) {
            jTextField1.setBorder(new LineBorder(Color.blue, 2));
            if (jTextField1.getText().trim().equals("")) {
                jTextField1.setText("Username");
                jTextField1.setForeground(Color.BLUE);
                tempLastText1 = 1;
            }
        } else if (evt.getSource() == jPasswordField1) {
            jPasswordField1.setBorder(new LineBorder(Color.blue, 2));
            if (jPasswordField1.getText().trim().equals("")) {
                jPasswordField1.setText("Password");
                jPasswordField1.setForeground(Color.BLUE);
                tempLastText2 = 1;
                jPasswordField1.setEchoChar('\u0000');
            }
        }
    }//GEN-LAST:event_jPasswordField1lostFocusField

    private void jPasswordField1enterField(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1enterField
        // TODO add your handling code here:
        if (evt.getSource() == jTextField1) {
            jTextField1.setFocusable(true);

        } else if (evt.getSource() == jPasswordField1) {
            jPasswordField1.setFocusable(true);

        }
    }//GEN-LAST:event_jPasswordField1enterField

    private void jPasswordField1fieldTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1fieldTyped
        // TODO add your handling code here:
        if (evt.getSource() == jTextField1) {
            tempFocused1 = 0;
            tempLastText1 = 0;
        } else if (evt.getSource() == jPasswordField1) {
            tempFocused2 = 0;
            tempLastText2 = 0;
        }
    }//GEN-LAST:event_jPasswordField1fieldTyped

    private void jPasswordField2fieldFocus(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2fieldFocus
        // TODO add your handling code here:
        jPasswordField2.setBorder(new LineBorder(Color.blue, 5));
        if (jPasswordField2.getText().trim().equals("") || tempFocused3 == 1 || tempLastText3 == 1) {
            jPasswordField2.setText("");
            jPasswordField2.setForeground(Color.black);
            jPasswordField2.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_jPasswordField2fieldFocus

    private void jPasswordField2lostFocusField(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2lostFocusField
        // TODO add your handling code here:
        jPasswordField2.setBorder(new LineBorder(Color.blue, 2));
        if (jPasswordField2.getText().trim().equals("")) {
            jPasswordField2.setText("Confirm Password");
            jPasswordField2.setForeground(Color.BLUE);
            tempLastText3 = 1;
            jPasswordField2.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_jPasswordField2lostFocusField

    private void jPasswordField2enterField(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2enterField
        // TODO add your handling code here:
        jPasswordField2.setFocusable(true);
    }//GEN-LAST:event_jPasswordField2enterField

    private void jPasswordField2fieldTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2fieldTyped
        // TODO add your handling code here:
        tempFocused3 = 0;
        tempLastText3 = 0;
    }//GEN-LAST:event_jPasswordField2fieldTyped

    private void enterGoBackButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterGoBackButton
        // TODO add your handling code here:
        jButton1.setBackground(Color.white);
        jButton1.setForeground(Color.red);
        jButton1.setBorder(new LineBorder(Color.red, 3));
    }//GEN-LAST:event_enterGoBackButton

    private void exitGoBackButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitGoBackButton
        // TODO add your handling code here:
        jButton1.setBackground(new Color(102, 102, 102));
        jButton1.setForeground(Color.white);
        jButton1.setBorder(new LineBorder(Color.white, 3));
    }//GEN-LAST:event_exitGoBackButton

    private void GoBackToLoginScreen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackToLoginScreen
        // TODO add your handling code here:
        dispose();
        new loginScreen().setVisible(true);
    }//GEN-LAST:event_GoBackToLoginScreen

    private void jButton2loginButtonHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2loginButtonHover
        // TODO add your handling code here:
        jButton2.setBackground(Color.BLUE);
    }//GEN-LAST:event_jButton2loginButtonHover

    private void jButton2loginButtonOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2loginButtonOut
        // TODO add your handling code here:
        jButton2.setBackground(Color.RED);
    }//GEN-LAST:event_jButton2loginButtonOut

    private boolean checkConfirmPassword(String pass, String cPass) {
        boolean temp=true;
        if(!(jPasswordField1.getForeground()==Color.black && jPasswordField2.getForeground()==Color.black)){
            temp=false;
        }
        if (pass.equals(cPass)) {
            if(temp){
                return true;
            }
        }
        else{
            temp=false;
        }
        return temp;
    }

    private boolean checkIfNotEmpty(String username, String pass, String cpass) {
        boolean temp=true;
        if(!(jTextField1.getForeground()==Color.black && jPasswordField1.getForeground()==Color.black && jPasswordField2.getForeground()==Color.black)){
            temp=false;
        }
        if (!(username.trim().equals("") && pass.trim().equals("") && cpass.trim().equals(""))) {
            if(temp){
                return true;
            }
        }
        return temp;
    }

    private boolean checkUsernameIfValid(String username) {
        int length = username.length();
        boolean temp = true;
        if (!(length >= 6 && length <= 12)) {
            temp = false;
        } else {
            for (int i = 0; i < length; i++) {
                if (!((username.charAt(i) >= 65 && username.charAt(i) <= 90) || (username.charAt(i) >= 97 && username.charAt(i) <= 122))) {
                    if (!(username.charAt(i) >= 48 && username.charAt(i) <= 57)) {
                        temp = false;
                        break;
                    }
                }
            }
        }
        return temp;
    }
    private boolean checkPasswordIfValid(String password){
        int length=password.length();
        boolean temp=true;
        if(!(length>=8 && length<=16)){
            temp=false;
        }
        else{
            for (int i = 0; i < length; i++) {
                if(password.charAt(i)== 32){
                    temp=false;
                    break;
                }
            }
        }
        return temp;
    }
    private void restart(){
        dispose();
        new createAccountScreen().setVisible(true);
    }
    private void succCreateAcc(String username , String password){
        String db="jdbc:mysql://localhost/allchat";
        String user="root";
        String pass="12345678";
        
        try{
            Connection conn=DriverManager.getConnection(db,user,pass);
            Statement stmt=conn.createStatement();
            String query="SELECT * FROM users WHERE BINARY username='"+username+"'";
            ResultSet result=stmt.executeQuery(query);
            if(result.next()){
                JOptionPane.showMessageDialog(null,"Username is already used.","Invalid",JOptionPane.WARNING_MESSAGE);
            }
            else{
                String query2="INSERT INTO users VALUES ('"+username+"','"+password+"','defaultUser','0')";
                stmt.executeUpdate(query2);
                restart();
                JOptionPane.showMessageDialog(null,"Successfully created your account.","Successful",JOptionPane.PLAIN_MESSAGE);
            }
            stmt.close();
            conn.close();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,""+ex.getMessage(),"Error" ,JOptionPane.ERROR_MESSAGE);
        }
        
    }
    private void createAccount(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccount

        String username = jTextField1.getText();
        String password = jPasswordField1.getText();
        String cPassword = jPasswordField2.getText();

        if (checkIfNotEmpty(username, password, cPassword)) {
            if (checkConfirmPassword(password, cPassword)) {
                if(checkUsernameIfValid(username)){
                    if(checkPasswordIfValid(password)){
                        succCreateAcc(username, password);
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Check password requirements.","Invalid Input",JOptionPane.ERROR_MESSAGE);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Check username requirements.","Invalid Input",JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Passwords doesn't match.", "Invalid Inputs", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Fields cannot be empty.", "Invalid Inputs", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_createAccount

    private void showUsernameReq(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showUsernameReq
        // TODO add your handling code here:
        String userReq="Username shoud not contain spaces , symbols and it should be at least 6 characters in length and at most 12.";
        JOptionPane.showMessageDialog(null,userReq,"Username Requirements",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_showUsernameReq

    private void showPassReq(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPassReq
        // TODO add your handling code here:
        String passReq="Password should not contain spaces , and it should be at least 8 characters in length and at most 16.";
        JOptionPane.showMessageDialog(null,passReq,"Password Requirements",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_showPassReq

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createAccountScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createAccountScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createAccountScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createAccountScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createAccountScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
